---
title: "Tidy Tuesday"
subtitle: "Alternative Fuel Stations over time" 
date: 2022-03-03
output: html_output
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidytuesdayR, tidyverse, statebins, geofacet)


```

# Loading data


```{r Load}

tt <- tt_load("2022-03-01")

data <- tt$stations

glimpse(data)
```

My goal here is to create a heatmap across decades for prevelancy of alternative fuel stations.

# Wrangle

First, grabbing only relavant variables and cleaning up date variable. I also need to extract only year.

```{r Wrangle}

data_r <-
data %>%
  janitor::clean_names() %>%
  select(state, open_date) %>%
  mutate(date = lubridate::as_date(open_date),
         year = lubridate::year(date)) %>%
  filter(!state %in% c("PR","DC","ON")) %>% ##Filtering to only include states
  select(state, year)

glimpse(data_r)

```
Now I need to get cumulative sum for each state over time.

```{r}

#tidycensus::census_api_key("b9ce69beb23da6572ecbfc670ba40ab0176478c7", install = TRUE)
library(tidycensus)

## getting state population data from census to normalize counts of stations. Using 2018 population for each year.
state_pop <- 
  get_acs(geography = "state", 
        variables = c("Total Population" = "B01001_001"),
        year = 2018, 
        survey = "acs1") %>%
  select(
    "state" = NAME,
    "pop" = estimate
  ) %>%
  filter(state != "District of Columbia",
         state != "Puerto Rico")

states <-   # Need to add state abbreviations to match with stations data
  tibble(
    state = datasets::state.abb,
    pop = state_pop$pop
  )


data_r <- 
data_r %>%
  inner_join(states) %>%
  arrange(-pop)


counts <- 
data_r %>%
    mutate(decade = case_when(
    between(year, 1970, 1980) ~ "1970s",
    between(year, 1980, 1990) ~ "1980s",
    between(year, 1990, 2000) ~ "1990s",
    between(year, 2000, 2010) ~ "2000s",
    between(year, 2010, 2020) ~ "2010s",
    year >= 2020 ~ "2020s"
  )) %>%
  group_by(decade) %>%
  add_count(state,sort = TRUE, drop = FALSE) %>% # get count for each state by year
  distinct(state, decade, pop, n) %>%
  arrange(state, decade) %>% #sort rows by state and year
  group_by(state) %>% 
  mutate(cumsum = cumsum(n), ## cumulative sum over years
         sum_percap = (cumsum(n)/pop),  ## cumulative sum per cap
         sum_per100k = sum_percap * 100000 ## cumulative sum per 100k people
         ) %>% # calc. cum. sum for each state over time
  select(state, decade, pop, cumsum, sum_percap, sum_per100k)

head(counts)

```


# Creating heatmap plot


```{r}
counts %>% 
  filter(!is.na(decade),
         decade %in% c("2000s", "2010s", "2020s")) %>%
  ggplot() +
  statebins::geom_statebins(aes(state = state,
                                fill = sum_per100k),
                            lbl_size = 1.9) +
  scale_fill_gradient(low = "midnight blue", high = "pink") +
  theme_statebins() +
  guides(fill = guide_legend(title = "Stations per 100k people")) +
  labs(
    title = "Alternative Fuel Station Prevalency Over time",
    x = NULL,
    y = NULL,
    caption = "\n Figure by: Sean Bock\n Data: US DOT\n Git: https://github.com/Sdbock/tidytuesday "
  )  +
  facet_wrap(~ decade, 
             strip.position = "bottom") +
  theme(
    plot.background = element_rect(fill = "white), # controlling background color for git
    strip.background = element_rect(color = "white"),
    strip.text = element_text(face = "bold", size = 12),
    plot.title = element_text(size = 14, face = "bold"),
    legend.key.size = unit(.25,"cm"),
    legend.title = element_text(size = 8),
    plot.caption = element_text(size = 8),
  )

```


# Saving Image


```{r}

# This will save your most recent plot
ggsave(
  filename = "figures/2022_03_01.png",
  device = "png",
  height = 5,
  width = 8)

```
