---
title: "Tidy Tuesday: Contextualizing Democratic Backslding with Freedom House and UN data"
date: 2022-02-22
output: html_output
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

if(!require(pacman)){
  install.packages("pacman")
}

pacman::p_load(tidyverse,tidytuesdayR, ggthemes, grid)

```

# Loading the weekly TidyTuesday Data

```{r Load}

tt <- tt_load("2022-02-22")

```

```{r Readme, eval = interactive()}

tt

```

Looking at data.

```{r Glimpse}

data <- tt$freedom

glimpse(data)
```

# Wrangling data

```{r Wrangle}

## reversing order of CL and PR variables
data <-
  data %>% 
  mutate(
    across(c(CL,PR), ~ 8 - .x)
    )

## getting regional means across years
region_means <- data %>%
  group_by(Region_Name, year) %>%
  summarize(
    mean_CL = mean(CL),
    mean_PR = mean(PR)
  ) 

```



```{r Visualize}

data %>%
  ggplot(aes(x = CL, y = PR, color = Region_Name)) +
  geom_jitter(data = . %>% filter(country != "United States of America"), color = "grey", alpha = .2) +
  geom_point(data = . %>% filter(country == "United States of America"), color = "red", size = 3) + 
  geom_point(data = region_means, aes(x = region_means$mean_CL, y = region_means$mean_PR, shape = region_means$Region_Name), inherit.aes = FALSE, color = "white", size = 3) +
  facet_wrap(~ year) +
  ggthemes::theme_clean() +
  guides(
    shape = guide_legend("Regional means")
  ) + 
  labs(
    x = "Civil Liberties",
    y = "Political Rights",
    title = "Contextualizing U.S. Democratic Backsliding",
    subtitle = str_wrap("Note: U.S. value indicated in red. Grey points (country observations) are jittered to avoid overlapping.",width = 40),
    caption = "\n Figure by: Sean Bock\n Data source: Freedom House and UN, provided by Arthur Cheib\n Git: https://github.com/Sdbock/tidytuesday "
  ) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    strip.background = element_rect(fill =  "black"),
    axis.title = element_text(color = "white", size = 15),
    strip.text = element_text(color = "white", size = 14),
    plot.title = element_text(color = "white", size = 18),
    plot.subtitle = element_text(color = "white", size = 10),
    plot.caption = element_text(color = "white", size = 10),
    plot.caption.position = "plot",
    legend.background = element_rect(fill = "black"),
    legend.text = element_text(color = "white", size = 14),
    legend.key = element_blank(),
    legend.title = element_text(color = "white"),
    axis.ticks = element_blank(),
    axis.line.y = element_line(color = "white",arrow = grid::arrow(length = unit(0.2, "cm"), 
                                                       ends = "last")),
    axis.line.x = element_line(color = "white",arrow = grid::arrow(length = unit(0.2, "cm"), 
                                                       ends = "last"))
  )

  
```

# Saving figure

```{r}

# This will save your most recent plot
ggsave(
  filename = "figures/2022_02_22_tidy_tuesday.png",
  device = "png")

```
